title: PMc Fabrication and Metalworks  # Name of the site
author:
  name: PMc Fabrication and Metalworks
metadata:
    description: 'PMc Fabrication and Metalworks'

# Header customization
header:
  title: PMc FABRICATION &amp; METALWORKS
  description:
  buttons:
    - text: "check out the studio"
      link: "#portfolio"
      class: "learn-more-btn"

footer:
  links:
    - text: Terms &amp; Conditions
      url: "#"
    - text: Legals
      url: "#"
